version = 1
SPDX-PackageName = "Generator-easy-ui5"
SPDX-PackageSupplier = "UI5 Community <https://github.com/ui5-community>"
SPDX-PackageDownloadLocation = "https://github.com/ui5-community/generator-easy-ui5"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2018-2025 SAP SE or an SAP affiliate company and generator-easy-ui5 contributors", "2025 UI5 Community and generator-easy-ui5 contributors"]
SPDX-License-Identifier = "Apache-2.0"
